// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShop.Data;

#nullable disable

namespace PetShop.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20221108140026_AddContent")]
    partial class AddContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetShop.Model.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            CategoryId = 1,
                            Discription = "The cat (Felis catus) is a domestic species of small carnivorous mammal.[1][2] It is the only domesticated species in the family Felidae and is commonly referred to as the domestic cat or house cat to distinguish it from the wild members of the family.[4] A cat can either be a house cat, a farm cat, or a feral cat; the feral cat ranges freely and avoids human contact.[5] Domestic cats are valued by humans for companionship and their ability to kill rodents. About 60 cat breeds are recognized by various cat registries.",
                            Name = "Cat",
                            PictureName = "https://www.rd.com/wp-content/uploads/2021/01/GettyImages-1175550351.jpg?resize=2048,1339"
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            CategoryId = 1,
                            Discription = "The dog (Canis familiaris or Canis lupus familiaris) is a domesticated descendant of the wolf. Also called the domestic dog, it is derived from the extinct Pleistocene wolf, and the modern wolf is the dog's nearest living relative. The dog was the first species to be domesticated, by hunter-gatherers over 15,000 years ago, before the development of agriculture. Due to their long association with humans, dogs have expanded to a large number of domestic individuals and gained the ability to thrive on a starch-rich diet that would be inadequate for other canids.",
                            Name = "Dog",
                            PictureName = "https://ichef.bbci.co.uk/news/976/cpsprodpb/17638/production/_124800859_gettyimages-817514614.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Age = 6,
                            CategoryId = 2,
                            Discription = "Turtles are an order of reptiles known as Testudines, characterized by a shell developed mainly from their ribs. Modern turtles are divided into two major groups, the Pleurodira (side necked turtles) and Cryptodira (hidden necked turtles), which differ in the way the head retracts. There are 360 living and recently extinct species of turtles, including land-dwelling tortoises and freshwater terrapins. They are found on most continents, some islands and, in the case of sea turtles, much of the ocean. Like other reptiles, birds, and mammals, they breathe air and do not lay eggs underwater, although many species live in or around water. ",
                            Name = "Turtle",
                            PictureName = "https://cdn.britannica.com/55/174255-050-526314B6/brown-Guernsey-cow.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Age = 7,
                            CategoryId = 2,
                            Discription = "The axolotl Classical Nahuatl: Ambystoma mexicanum, is a paedomorphic salamander closely related to the tiger salamander. Axolotls are unusual among amphibians in that they reach adulthood without undergoing metamorphosis. Instead of taking to the land, adults remain aquatic and gilled. The species was originally found in several lakes underlying what is now Mexico City, such as Lake Xochimilco and Lake Chalco. These lakes were drained by Spanish settlers after the conquest of the Aztec Empire, leading to the destruction of much of the axolotl’s natural habitat.",
                            Name = "Axolotl",
                            PictureName = "https://cdn.britannica.com/66/195966-138-F9E7A828/facts-turtles.jpg?w=800&h=450&c=crop"
                        },
                        new
                        {
                            Id = 5,
                            Age = 1,
                            CategoryId = 3,
                            Discription = "Clownfish or anemonefish are fishes from the subfamily Amphiprioninae in the family Pomacentridae. Thirty species of clownfish are recognized: one in the genus Premnas, while the remaining are in the genus Amphiprion. In the wild, they all form symbiotic mutualisms with sea anemones. Depending on species, anemonefish are overall yellow, orange, or a reddish or blackish color, and many show white bars or patches.",
                            Name = "Clownfish",
                            PictureName = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg/640px-Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Age = 2,
                            CategoryId = 3,
                            Discription = "Pterois is a genus of venomous marine fish, commonly known as lionfish, native to the Indo-Pacific. Also called firefish, turkeyfish, tastyfish, or butterfly-cod, it is characterized by conspicuous warning coloration with red, white, creamy, or black bands, showy pectoral fins, and venomous, spiky fin rays.",
                            Name = "Lionfish",
                            PictureName = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Red_lionfish_near_Gilli_Banta_Island.JPG/1280px-Red_lionfish_near_Gilli_Banta_Island.JPG"
                        },
                        new
                        {
                            Id = 7,
                            Age = 6,
                            CategoryId = 4,
                            Discription = "Eagle is the common name for many large birds of prey of the family Accipitridae. Eagles belong to several groups of genera, some of which are closely related. Most of the 60 species of eagle are from Eurasia and Africa.[1] Outside this area, just 14 species can be found—2 in North America, 9 in Central and South America, and 3 in Australia. ",
                            Name = "Eagle",
                            PictureName = "https://a-z-animals.com/media/2019/11/Eagle-header.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Age = 3,
                            CategoryId = 4,
                            Discription = "A cockatoo is any of the 21 parrot species belonging to the family Cacatuidae, the only family in the superfamily Cacatuoidea. Along with the Psittacoidea (true parrots) and the Strigopoidea (large New Zealand parrots), they make up the order Psittaciformes. The family has a mainly Australasian distribution, ranging from the Philippines and the eastern Indonesian islands of Wallacea to New Guinea, the Solomon Islands and Australia. ",
                            Name = "Cockatoo",
                            PictureName = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Eolophus_roseicapilla_-Wamboin%2C_NSW%2C_Australia_-adult-8-2cp.jpg/800px-Eolophus_roseicapilla_-Wamboin%2C_NSW%2C_Australia_-adult-8-2cp.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Age = 1,
                            CategoryId = 5,
                            Discription = "Bees are winged insects closely related to wasps and ants, known for their roles in pollination and, in the case of the best-known bee species, the western honey bee, for producing honey. Bees are a monophyletic lineage within the superfamily Apoidea. They are presently considered a clade, called Anthophila. There are over 16,000 known species of bees in seven recognized biological families.[1][2] Some species – including honey bees, bumblebees, and stingless bees – live socially in colonies while most species (>90%) – including mason bees, carpenter bees, leafcutter bees, and sweat bees – are solitary. ",
                            Name = "Bee",
                            PictureName = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Anthidium_February_2008-1.jpg/1280px-Anthidium_February_2008-1.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Age = 2,
                            CategoryId = 5,
                            Discription = "Mantises are an order of insects that contains over 2,400 species in about 460 genera in 33 families. The largest family is the Mantidae. Mantises are distributed worldwide in temperate and tropical habitats. They have triangular heads with bulging eyes supported on flexible necks.",
                            Name = "Mantis",
                            PictureName = "https://inaturalist-open-data.s3.amazonaws.com/photos/180063407/original.jpg"
                        });
                });

            modelBuilder.Entity("PetShop.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mammal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Reptile"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bird"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amphibian"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Invertebrates"
                        });
                });

            modelBuilder.Entity("PetShop.Model.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            Comment = "Good"
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 2,
                            Comment = "Good"
                        },
                        new
                        {
                            Id = 11,
                            AnimalId = 1,
                            Comment = "Wow"
                        },
                        new
                        {
                            Id = 12,
                            AnimalId = 2,
                            Comment = "Wow"
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 3,
                            Comment = "Nice"
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 4,
                            Comment = "Nice"
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = 5,
                            Comment = "Very good"
                        },
                        new
                        {
                            Id = 6,
                            AnimalId = 6,
                            Comment = "Very good"
                        },
                        new
                        {
                            Id = 7,
                            AnimalId = 7,
                            Comment = "Super"
                        },
                        new
                        {
                            Id = 8,
                            AnimalId = 8,
                            Comment = "Super"
                        },
                        new
                        {
                            Id = 9,
                            AnimalId = 9,
                            Comment = "Buteful"
                        },
                        new
                        {
                            Id = 10,
                            AnimalId = 10,
                            Comment = "Buteful"
                        });
                });

            modelBuilder.Entity("PetShop.Model.Animal", b =>
                {
                    b.HasOne("PetShop.Model.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PetShop.Model.Comments", b =>
                {
                    b.HasOne("PetShop.Model.Animal", "Animal")
                        .WithMany("Comments")
                        .HasForeignKey("AnimalId");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PetShop.Model.Animal", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PetShop.Model.Category", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
